
version: 2

sources:
  - name: sch_stg
    database: db_cf_edw
    schema: sch_stg
    tables:
      - name: writingcompany


models:
    - name: stg_coverage
      config:
        tags: 
          - tag_in_schema
      description: coverage staging table
      columns:
          - name: policy_key
    - name: stg_policy
      config:
        tags: 
          - tag_in_schema    
      description: policy staging table
      columns:
          - name: policy_specification_key