{{config ( 
    materialized ='table',
    tags =["tag_in_code","premium_financial"]
)}}

with pre_fin_tran_details_fc as (
select distinct clslmt CLASS_LIMIT_CD, CLASX EXPOSURE_CLASS_CD, INDRMOD INDIVIDUAL_RISK_RATING_MODIFICATION, 
LEXPIND TYPE_OF_EXPOSURE_GL, LOSCDT  LOSS_COST_DT, SICCDE NAICS_CD, NUMPRE NUMBER_OF_ADDITIONAL_LOCATIONS,
NUMREM NUMBER_OF_RATABLE_EMPLOYESS, NUMEMPL TOTAL_NUMBER_OF_EMPLOYESS,POLFRM POLICY_FORM,
 date(nvl(nullifzero(RATDTE),99991231),'YYYYMMDD') RATE_DT,RTEDEP RATE_DEPARTURE_FACTOR_CD, 
PIPRAT RATING_BASIS_IND,RTEGRP RATING_GROUP_CD, RATEID RATING_ID_CD , 
APPLIM RATING_UNIT_VALUE_CD,SCHMODF SCHEDULE_RATING_MODIFICATION_FACTOR_CD,
STEEXC STATE_EXCEPTION_CD,EARTHQ STATE_EXCEPTION_CD_II,EXCEPT STATE_EXCEPTION_CD_II_BOP,
LIMCDE POLICY_LIMIT_CD_GL,'NA' RATE_MODE_CD,'NA' RATE_MODIFICATION_FACTOR_CD,'NA' STATE_EXCEPTION_CD_TYPE,
ZNERTE ZONE_RATING_ID_CD, COVERG COVERAGE_DECLARATION_PAGE_CD, PREMID PART_OF_PREMIUM_IND,
POLTYP POLICY_TYPE_ISO_CD

from "DBT_STAGE"."DBT_ASHAHU"."WINSFC_DWXP050" )
--from "PRD_CAESAR_RL_DB"."WINSFC"."DWXP050")
select   CLASS_LIMIT_CD,  EXPOSURE_CLASS_CD,  INDIVIDUAL_RISK_RATING_MODIFICATION, 
 TYPE_OF_EXPOSURE_GL,   LOSS_COST_DT,  NAICS_CD,  NUMBER_OF_ADDITIONAL_LOCATIONS,
 NUMBER_OF_RATABLE_EMPLOYESS,  TOTAL_NUMBER_OF_EMPLOYESS, POLICY_FORM,
 RATE_DT, RATE_DEPARTURE_FACTOR_CD, RATING_BASIS_IND, RATING_GROUP_CD,  RATING_ID_CD , 
 RATING_UNIT_VALUE_CD, SCHEDULE_RATING_MODIFICATION_FACTOR_CD,STATE_EXCEPTION_CD, 
 STATE_EXCEPTION_CD_II, STATE_EXCEPTION_CD_II_BOP,POLICY_LIMIT_CD_GL, RATE_MODE_CD, 
 RATE_MODIFICATION_FACTOR_CD, STATE_EXCEPTION_CD_TYPE,ZONE_RATING_ID_CD,  
 COVERAGE_DECLARATION_PAGE_CD,  PART_OF_PREMIUM_IND, POLICY_TYPE_ISO_CD,
 sha2(concat( CLASS_LIMIT_CD,'||',  EXPOSURE_CLASS_CD,'||',  INDIVIDUAL_RISK_RATING_MODIFICATION,'||', 
 TYPE_OF_EXPOSURE_GL,'||',   LOSS_COST_DT,'||',  NAICS_CD, '||', NUMBER_OF_ADDITIONAL_LOCATIONS,'||',
 NUMBER_OF_RATABLE_EMPLOYESS,'||',  TOTAL_NUMBER_OF_EMPLOYESS,'||', POLICY_FORM,'||',
 RATE_DT,'||', RATE_DEPARTURE_FACTOR_CD,'||', RATING_BASIS_IND,'||', RATING_GROUP_CD,'||',  RATING_ID_CD ,'||', 
 RATING_UNIT_VALUE_CD,'||', SCHEDULE_RATING_MODIFICATION_FACTOR_CD,'||', STATE_EXCEPTION_CD,'||', 
 STATE_EXCEPTION_CD_II,'||', STATE_EXCEPTION_CD_II_BOP,'||', POLICY_LIMIT_CD_GL,'||', RATE_MODE_CD,'||', 
 RATE_MODIFICATION_FACTOR_CD,'||', STATE_EXCEPTION_CD_TYPE,'||', ZONE_RATING_ID_CD,'||',  
 COVERAGE_DECLARATION_PAGE_CD,'||',  PART_OF_PREMIUM_IND,'||', POLICY_TYPE_ISO_CD)) sha2_record
 from pre_fin_tran_details_fc